services:
  bp_sync:
    image: vlnag/bolashaq_sync
    env_file:
      - .env
    volumes:
      - code-data:/opt/app/data
      - logs-data:/opt/app/logs
    ports:
     - 8080:8080
    depends_on:
      db:
        condition: service_healthy

  bp_sync-migrations:
    image: vlnag/bolashaq_sync
    env_file:
      - .env
    restart: no
    depends_on:
      db:
        condition: service_healthy
    command: alembic upgrade head

  db:
    image: postgres:17.4-bookworm
    restart: always
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      retries: 5
      start_period: 0s
      timeout: 10s

  redis:
    image: redis:7-alpine
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: redis-server --requirepass ${REDIS_PASSWORD} --save 60 1 --appendonly yes
    volumes:
      - redis-data:/data

  rabbitmq:
    hostname: rabbitmq
    image: rabbitmq:3.12-management
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBIT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBIT_PASSWORD}
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  email-worker:
    image: vlnag/bolashaq_email_worker
    restart: unless-stopped
    environment:
      - LOG_LEVEL=INFO
    env_file:
      - .env.mail
    depends_on:
      rabbitmq:
        condition: service_healthy

volumes:
  db_data:
  redis-data:
  code-data:
  logs-data:
  rabbitmq-data:
